import { defineType, defineField } from 'sanity';

export default defineType({
  name: 'authorInfo',
  title: 'Author Information',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Author Name',
      type: 'string',
      description: 'The name displayed across the site (usually the pen name)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      description: 'Short descriptor, e.g. "Author of psychological suspense"',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Contact Email',
      type: 'string',
      description:
        'Where contact-form messages are forwarded. Never displayed on the site.',
      validation: (Rule) => Rule.required().email(),
    }),
    defineField({
      name: 'shortBio',
      title: 'Short Bio',
      type: 'text',
      rows: 3,
      description: 'One or two sentences — used as the intro on the About page',
    }),
    defineField({
      name: 'longBio',
      title: 'Long Bio',
      type: 'text',
      rows: 12,
      description: 'The full story. Separate paragraphs with a blank line.',
    }),
    defineField({
      name: 'socials',
      title: 'Social Links',
      type: 'object',
      description: 'Leave any field blank to hide that icon',
      options: { collapsible: true, collapsed: false },
      fields: [
        { name: 'instagram', title: 'Instagram URL', type: 'url' },
        { name: 'facebook', title: 'Facebook URL', type: 'url' },
        { name: 'tiktok', title: 'TikTok URL', type: 'url' },
        { name: 'twitter', title: 'X / Twitter URL', type: 'url' },
        { name: 'goodreads', title: 'Goodreads URL', type: 'url' },
        { name: 'bookbub', title: 'BookBub URL', type: 'url' },
        { name: 'newsletter', title: 'Newsletter Signup URL', type: 'url' },
      ],
    } as any),
    defineField({
      name: 'logo',
      title: 'Logo / Wordmark',
      type: 'image',
      description: 'Displayed in the header and footer',
      options: { hotspot: true },
      fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
    }),
    defineField({
      name: 'portrait',
      title: 'Author Portrait',
      type: 'image',
      description: 'Photo of the author for the About section',
      options: { hotspot: true },
      fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
    }),
    defineField({
      name: 'booksImage',
      title: 'Books Section Image',
      type: 'image',
      description: 'Optional image beside the books list on the home page',
      options: { hotspot: true },
      fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
    }),
    defineField({
      name: 'aboutImage',
      title: 'About Section Background',
      type: 'image',
      description: 'Background photo for the about statement on the home page',
      options: { hotspot: true },
      fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }],
    }),
  ],
  preview: {
    select: { title: 'name' },
  },
});
